### ISSUE TITLE
Usunąć dwa ostatnie commity (5f8d86c, 0ac9fec)

### ISSUE THREAD

**Issue by kklimexk** [Vilgefortzz/Game-Writing#1]
Zadanie polega na usunięciu dwóch ostatnich commitow z repo na githubie.

Wystarczy użyć tej komendy: 

```
git push -f origin HEAD^^:master
```

Na końcu zweryfikować poleceniem: 

```
git status
```

Powinno się pokazać coś takiego:

```
Your branch is ahead of 'origin/master' by 2 commits.
```

I wtedy trzeba jeszcze usunąć te commity lokalnie poleceniem:

```
git reset --hard HEAD~2
```

I znowu zweryfikować statusem i powinno pojawić się coś takiego:

```
Your branch is up-to-date with 'origin/master'.
```

**Comment by Vilgefortzz** [comment]
Zadanie ukończone, wszystko uporządkowane ;)
